### ISSUE TITLE
Pingpong animations don't import properly for looping

### ISSUE THREAD

**Issue by BanchouBoo** [hectorid/aseprite_importer#1]
Say I have a 3 frame pingpong animation, the way it would play in aseprite is: `1 2 3 2 1 2 3 2 1`

But the way the importer will play the animation, if you turn on looping, is: `1 2 3 3 2 1 1 2 3 3 2 1`

When importing the pingpong animation, it seems as though you just take the animation, duplicate it, then reverse and append it. The way to fix this should just be to do that, but without duplicating the first and last frame.

**Comment by hectorid** [comment]
Actually i tested it in Aseprite and it does duplicate the first and last frames of the animation (you can clearly see it when you increase the frames duration).

But i guess it would be better if there was an option to enable the duplication or not.

**Comment by BanchouBoo** [comment]
If you look [here](https://streamable.com/kfsnlz), you can clearly see a difference between the animation in Godot vs in Aseprite.
