### ISSUE TITLE
Getting JSON_PARSE_ERROR when frameTags is empty in json.

### ISSUE THREAD

**Issue by geekrelief** [hectorid/aseprite_importer#6]
I followed the instructions: exported a JSON file from Aseprite, but when I try to import the json I get:

```
 res://addons/aseprite_importer/interface/import_menu/JSONImportMenu.gd:59 - Invalid get index 'JSON_PARSE_ERROR' (on base: 'Dictionary').
```

This is really strange because the json is valid:

```
{ "frames": {
   "particles 0.aseprite": {
    "frame": { "x": 0, "y": 0, "w": 8, "h": 8 },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 8, "h": 8 },
    "sourceSize": { "w": 8, "h": 8 },
    "duration": 100
   },
   "particles 1.aseprite": {
    "frame": { "x": 8, "y": 0, "w": 8, "h": 8 },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 8, "h": 8 },
    "sourceSize": { "w": 8, "h": 8 },
    "duration": 100
   }
 },
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.2.24-x64",
  "image": "particles.png",
  "format": "I8",
  "size": { "w": 16, "h": 8 },
  "scale": "1",
  "frameTags": [
  ],
  "layers": [
   { "name": "Layer 1", "opacity": 255, "blendMode": "normal" }
  ],
  "slices": [
  ]
 }
}
```

**Comment by geekrelief** [comment]
Hmm looks like it's failing validating the meta template because frameTags is empty.  I guess chalk this issue up to user error. Maybe there should be an appropriate error message for this or just leave this issue open?  

For anyone else new to Asesprite, tags are how you reference your animations, so add your tags to your frames so they can referenced in Godot.

**Comment by geekrelief** [comment]
Looks like there was an error with the plugin code, I created a PR #7 
Now the json above will show an error message. 
![Annotation 2020-08-16 092544](https://user-images.githubusercontent.com/27040/90338998-a12d0680-dfa2-11ea-9259-fcdb8b817690.png)

**Comment by hectorid** [comment]
Yep, thanks for spotting that. I've merged your modifications but i'm going to change the messages a little bit before creating a new release.
